"""
Reviewer Agent
Evaluates code diffs, pull requests, and proposed fixes for correctness, logic bugs, security vulnerabilities, performance, and regression risks.
"""
from typing import Dict, Any, List, Optional
from agent_tracer import AgentTracer


class ReviewerAgent:
    """
    Quality assurance and security review agent.
    """

    def __init__(self, tracer: Optional[AgentTracer] = None):
        self.name = "Reviewer Agent"
        self.tracer = tracer

    def review_pr(
        self,
        pr_data: Dict[str, Any],
        repo_context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Perform comprehensive code review on a GitHub Pull Request."""
        number = pr_data.get("number", 0)
        title = pr_data.get("title", "")
        changed_files = pr_data.get("changed_files", [])

        critical_issues = []
        warnings = []
        suggestions = []
        positive_observations = []
        missing_tests = []

        if not changed_files:
            warnings.append({
                "severity": "MEDIUM",
                "file": "PR Metadata",
                "location": "Global",
                "explanation": "No changed files were detected in this PR.",
                "recommended_fix": "Verify that commits are pushed to the head branch."
            })

        has_tests = False
        for f in changed_files:
            fname = f.get("filename", "")
            patch = f.get("patch", "")

            if "test" in fname.lower():
                has_tests = True
                positive_observations.append(f"PR includes updated test file: {fname}")

            # Check for common vulnerabilities or bad practices
            if "Your GitHub Token" in patch or "sk-" in patch:
                critical_issues.append({
                    "severity": "CRITICAL",
                    "file": fname,
                    "location": "Diff Patch",
                    "explanation": "Hardcoded API key or credential string detected in code patch.",
                    "recommended_fix": "Use environment variable loading `os.getenv(...)` instead of string literal."
                })

            if "print(" in patch:
                suggestions.append({
                    "severity": "LOW",
                    "file": fname,
                    "location": "Diff Patch",
                    "explanation": "Raw print statements present; consider using structured logging.",
                    "recommended_fix": "Replace `print(...)` with `logging.getLogger(...)`."
                })

        if not has_tests:
            missing_tests.append({
                "severity": "HIGH",
                "file": "Test Suite",
                "location": "Global",
                "explanation": "PR modifies core implementation files without adding or updating unit tests.",
                "recommended_fix": "Add corresponding tests using the Test Agent."
            })

        overall_assessment = "APPROVED WITH SUGGESTIONS" if not critical_issues else "NEEDS REVISION"
        
        review_output = {
            "pr_number": number,
            "title": title,
            "overall_assessment": overall_assessment,
            "critical_issues": critical_issues,
            "warnings": warnings,
            "suggestions": suggestions,
            "positive_observations": positive_observations,
            "missing_tests": missing_tests,
            "final_recommendation": "Merge after addressing critical findings and adding test coverage." if not critical_issues else "Block merge until hardcoded credentials and critical findings are resolved."
        }

        if self.tracer:
            self.tracer.log_step(
                agent_name=self.name,
                action=f"Completed PR #{number} Code Review ({overall_assessment})",
                tool_output=review_output
            )

        return review_output

    def review_proposed_patch(
        self,
        patch_plan: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Review a code patch generated by the Coder Agent prior to human approval."""
        target_file = patch_plan.get("target_file", "")
        modified = patch_plan.get("modified_content", "")

        is_safe = True
        findings = []

        if "Your GitHub Token" in modified:
            is_safe = False
            findings.append("Hardcoded placeholder string found in modified content.")

        review_res = {
            "is_approved": is_safe,
            "findings": findings,
            "recommendation": "Safe for human approval." if is_safe else "Requires patch adjustments."
        }

        if self.tracer:
            self.tracer.log_step(
                agent_name=self.name,
                action=f"Reviewed proposed patch for {target_file} (Approved: {is_safe})",
                tool_output=review_res
            )

        return review_res
